name: wait-for-deployment-action
description: Wait for GitHub Deployment

inputs:
  filter-environments:
    description: Filter deployments by environment patterns (multiline)
    required: false
  exclude-environments:
    description: Exclude deployments by environment patterns (multiline)
    required: false
  until:
    description: Either completed or succeeded
    required: false
  initial-delay-seconds:
    description: Initial delay before polling in seconds
    required: true
    default: '10'
  period-seconds:
    description: Polling interval in seconds
    required: true
    default: '15'
  timeout-seconds:
    description: If set, poll until the timeout
    required: false
  deployment-sha:
    description: Find the deployments of the commit
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  progressing:
    description: Whether any deployment is progressing
  failed:
    description: Whether any deployment is failed
  completed:
    description: Whether all deployments are completed
  succeeded:
    description: Whether all deployments are succeeded
  summary:
    description: Markdown list of all deployments
  json:
    description: JSON representation of all deployments

runs:
  using: 'node20'
  main: 'dist/index.js'
