name: wait-for-deployment-action
description: Aggregate GitHub Deployments against commit SHA

inputs:
  until:
    description: Either completed or succeeded
    required: false
  initial-delay-seconds:
    description: Initial delay before polling in seconds
    required: true
    default: '10'
  period-seconds:
    description: Polling period in seconds
    required: true
    default: '15'
  deployment-sha:
    description: Find deployments by commit
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  progressing:
    description: true if any deployment is progressing
  failed:
    description: true if any deployment is failed
  completed:
    description: true if all deployments are completed
  succeeded:
    description: true if all deployments are succeeded
  summary:
    description: markdown list of all deployments

runs:
  using: 'node20'
  main: 'dist/index.js'
