name: wait-for-deployment-action
description: Aggregate GitHub Deployments against commit SHA

inputs:
  wait-until:
    description: If set, wait for the status either completed or succeeded
    required: false
  wait-initial-delay-seconds:
    description: Initial delay before polling in seconds
    required: true
    default: '10'
  wait-period-seconds:
    description: Polling period in seconds
    required: true
    default: '15'
  sha:
    description: Commit SHA or ref
    required: true
    default: ${{ github.event.pull_request.head.sha || github.sha }}
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  progressing:
    description: true if any deployment is progressing
  failed:
    description: true if any deployment is failed
  completed:
    description: true if all deployments are completed
  succeeded:
    description: true if all deployments are succeeded
  summary:
    description: markdown list of all deployments

runs:
  using: 'node20'
  main: 'dist/index.js'
