name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - '*.config.*'
      - graphql-codegen.*
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - '*.config.*'
      - graphql-codegen.*
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm run test

  create-deployments:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      app1: ${{ steps.app1.outputs.id }}
      app2: ${{ steps.app2.outputs.id }}
      app3: ${{ steps.app3.outputs.id }}
    steps:
      - uses: int128/deployment-action@2fef45e2234199384275d1186f058e9158ee0339 # v1.54.0
        id: app1
        with:
          environment-suffix: /app1
      - uses: int128/deployment-action@2fef45e2234199384275d1186f058e9158ee0339 # v1.54.0
        id: app2
        with:
          environment-suffix: /app2
          task: deploy
      - uses: int128/deployment-action@2fef45e2234199384275d1186f058e9158ee0339 # v1.54.0
        id: app3
        with:
          environment-suffix: /app3

  create-deployment-statuses:
    needs: create-deployments
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: sleep 15
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app1 }}
        with:
          script: |
            const { data: deploymentStatus } = await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app1`,
            })
            core.info(JSON.stringify(deploymentStatus, null, 2))
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app2 }}
        with:
          script: |
            const { data: deploymentStatus } = await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app2`,
            })
            core.info(JSON.stringify(deploymentStatus, null, 2))
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          deployment_id: ${{ needs.create-deployments.outputs.app3 }}
        with:
          script: |
            const { data: deploymentStatus } = await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: process.env.deployment_id,
              state: 'success',
              log_url: `https://argocd.example.com/pr-${context.issue.number}--app3`,
            })
            core.info(JSON.stringify(deploymentStatus, null, 2))

  wait-for-deployment:
    needs: create-deployments
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build
      - name: Run int128/wait-for-deployment-action
        id: wait-for-deployment
        uses: ./
        with:
          until: completed
          deployment-sha: ${{ github.event.pull_request.head.sha || github.sha }}
          initial-delay-seconds: 0
          period-seconds: 3
      - run: jq . <<< "$deployments"
        env:
          deployments: ${{ steps.wait-for-deployment.outputs.json }}
      - name: Check if total-count is 3
        if: steps.wait-for-deployment.outputs.total-count < 3
        run: exit 1

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .node-version
          package-manager-cache: false
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm run check
      - run: pnpm graphql-codegen
      - uses: int128/update-generated-files-action@2dfdf7949b8e414b6b014b636a2ebaa2f3c04fe9 # v2.77.0
